import torch

DEVICE=torch.device("cuda:0" if torch.cuda.is_available() else 'cpu')
BATCH_SIZE=1
NUM_TOKENS=30522
SHUFFLE=False
NUM_WORKERS=4
HIDDEN_FEATURE_SIZE=49152
HIDDEN_LAYER_SIZE=4092
INPUT_LAYER_SIZE=3072
OUTPUT_LAYER_SIZE=NUM_TOKENS
LEARNING_RATE=1e-4
SPACY_VOCABULARY='en_core_web_lg'